import type { DesignSystemPreset } from '../types';

export const presets: DesignSystemPreset[] = [
  {
    id: 'modern-saas',
    name: 'Modern SaaS (Slate & Violet)',
    description: 'Clean, elegant, minimalist theme matching modern SaaS apps like Shadcn or Linear. Excellent contrast and readability.',
    tokens: {
      name: 'Aura UI',
      author: 'Design Engine',
      description: 'Clean slate tones and indigo accents for professional dashboards.',
      version: '1.0.0',
      targetFramework: 'react-tailwind',
      colors: {
        primary: { light: '#6366f1', dark: '#818cf8', description: 'Brand primary action color' },
        primaryHover: { light: '#4f46e5', dark: '#6366f1', description: 'Brand primary action hover' },
        secondary: { light: '#64748b', dark: '#94a3b8', description: 'Secondary UI actions' },
        secondaryHover: { light: '#475569', dark: '#cbd5e1', description: 'Secondary UI actions hover' },
        accent: { light: '#a855f7', dark: '#c084fc', description: 'Special callout accents' },
        bg: { light: '#f8fafc', dark: '#0b0f19', description: 'Main screen background' },
        card: { light: '#ffffff', dark: '#111827', description: 'Surface element panels' },
        border: { light: '#e2e8f0', dark: '#1f2937', description: 'Standard borders and dividers' },
        text: { light: '#0f172a', dark: '#f8fafc', description: 'High contrast text color' },
        textMuted: { light: '#64748b', dark: '#94a3b8', description: 'Low contrast secondary labels' },
        success: { light: '#10b981', dark: '#34d399', description: 'Validation success states' },
        warning: { light: '#f59e0b', dark: '#fbbf24', description: 'Warning/Caution alerts' },
        error: { light: '#ef4444', dark: '#f87171', description: 'Error/Validation failure states' },
        info: { light: '#3b82f6', dark: '#60a5fa', description: 'Informational banner notifications' },
      },
      typography: {
        fontFamily: "'Inter', sans-serif",
        baseSize: 16,
        scaleFactor: 1.2, // Minor Third
        lineHeight: '1.5',
        letterSpacing: '-0.011em',
      },
      spacing: {
        baseUnit: 4,
        scale: [1, 2, 3, 4, 5, 6, 8, 10, 12, 16],
      },
      radius: {
        none: '0px',
        xs: '2px',
        sm: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
        xxl: '16px',
        full: '9999px',
        button: 'var(--radius-md)',
      },
      shadows: {
        none: 'none',
        sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        focus: '0 0 0 2px #fff, 0 0 0 4px #6366f1',
      },
      motion: {
        durationFast: '150ms',
        durationNormal: '250ms',
        durationSlow: '400ms',
        easeDefault: 'cubic-bezier(0.4, 0, 0.2, 1)',
        easeIn: 'cubic-bezier(0.4, 0, 1, 1)',
        easeOut: 'cubic-bezier(0, 0, 0.2, 1)',
        easeInOut: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      icons: {
        sizeSm: '14px',
        sizeMd: '18px',
        sizeLg: '24px',
        strokeWidth: '1.5px',
      },
    },
  },
  {
    id: 'material-3',
    name: 'Material 3 Design',
    description: 'Dynamic tonal color system inspired by Material Design 3. Very organic shapes, circular buttons, and soft, natural depths.',
    tokens: {
      name: 'Dynamic Material',
      author: 'Material Architect',
      description: 'Tonal variations and rounded cards styled to look like Android 13/14 UI.',
      version: '1.0.0',
      targetFramework: 'react-tailwind',
      colors: {
        primary: { light: '#6750a4', dark: '#d0bcff', description: 'Primary brand action' },
        primaryHover: { light: '#583f94', dark: '#bca6ed', description: 'Primary action hover' },
        secondary: { light: '#625b71', dark: '#ccc2dc', description: 'Secondary actions' },
        secondaryHover: { light: '#514a5e', dark: '#b0a6bf', description: 'Secondary action hover' },
        accent: { light: '#7d5260', dark: '#efb8c8', description: 'Tertiary dynamic accent' },
        bg: { light: '#fef7ff', dark: '#141218', description: 'Background surface' },
        card: { light: '#f3edf7', dark: '#211f26', description: 'Elevated surface card' },
        border: { light: '#c4c7eb', dark: '#49454f', description: 'Outlined container border' },
        text: { light: '#1d1b20', dark: '#e6e1e5', description: 'High contrast content color' },
        textMuted: { light: '#49454f', dark: '#cac4d0', description: 'Tonal secondary text' },
        success: { light: '#2e7d32', dark: '#81c784', description: 'Positive feedback state' },
        warning: { light: '#ed6c02', dark: '#ffb74d', description: 'Warning indicators' },
        error: { light: '#b3261e', dark: '#f2b8b5', description: 'Error state' },
        info: { light: '#0288d1', dark: '#4fc3f7', description: 'Info details' },
      },
      typography: {
        fontFamily: "'Roboto', 'Inter', sans-serif",
        baseSize: 16,
        scaleFactor: 1.25, // Major Third
        lineHeight: '1.4',
        letterSpacing: '0.007em',
      },
      spacing: {
        baseUnit: 8,
        scale: [1, 2, 3, 4, 5, 6, 8, 10, 12, 16],
      },
      radius: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        xxl: '28px',
        full: '9999px',
        button: 'var(--radius-full)',
      },
      shadows: {
        none: 'none',
        sm: '0px 1px 3px 1px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.3)',
        md: '0px 2px 6px 2px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.3)',
        lg: '0px 1px 8px 3px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.3)',
        xl: '0px 4px 12px 6px rgba(0, 0, 0, 0.15), 0px 8px 12px 6px rgba(0, 0, 0, 0.15)',
        focus: '0 0 0 3px #d0bcff',
      },
      motion: {
        durationFast: '100ms',
        durationNormal: '300ms',
        durationSlow: '600ms',
        easeDefault: 'cubic-bezier(0.2, 0, 0, 1)',
        easeIn: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
        easeOut: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
        easeInOut: 'cubic-bezier(0.2, 0, 0, 1)',
      },
      icons: {
        sizeSm: '18px',
        sizeMd: '24px',
        sizeLg: '32px',
        strokeWidth: '2px',
      },
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    description: 'High-energy, hyper-saturated neon themes with neon cyan, bright magenta, sharp edges, and retro sci-fi typography.',
    tokens: {
      name: 'Cyber Core',
      author: 'Net Runner',
      description: 'Bright saturated colors and pitch dark backdrops matching arcade and synthwave aesthetics.',
      version: '2.0.4',
      targetFramework: 'react-tailwind',
      colors: {
        primary: { light: '#ff0055', dark: '#ff0055', description: 'Cyber primary pink' },
        primaryHover: { light: '#cc0044', dark: '#ff3377', description: 'Cyber primary hover' },
        secondary: { light: '#00ffcc', dark: '#00ffcc', description: 'Cyber auxiliary cyan' },
        secondaryHover: { light: '#00cca3', dark: '#33ffd6', description: 'Cyber secondary hover' },
        accent: { light: '#ffff00', dark: '#ffff00', description: 'Screaming yellow hazard accent' },
        bg: { light: '#f4f5f6', dark: '#030308', description: 'Core dark mainframe backdrop' },
        card: { light: '#ffffff', dark: '#0c0b16', description: 'Subsystem component housing' },
        border: { light: '#e1e2e4', dark: '#ff0055', description: 'Primary system border (glow lines)' },
        text: { light: '#030308', dark: '#00ffcc', description: 'Main output font color' },
        textMuted: { light: '#737475', dark: '#9b9aa3', description: 'Hex/Logs minor readout text' },
        success: { light: '#39ff14', dark: '#39ff14', description: 'Success flag' },
        warning: { light: '#ffff00', dark: '#ffff00', description: 'Warning flag' },
        error: { light: '#ff073a', dark: '#ff073a', description: 'Error flag' },
        info: { light: '#00f0ff', dark: '#00f0ff', description: 'System notification banner' },
      },
      typography: {
        fontFamily: "'JetBrains Mono', monospace",
        baseSize: 15,
        scaleFactor: 1.15, // Golden ratio small
        lineHeight: '1.3',
        letterSpacing: '0.04em',
      },
      spacing: {
        baseUnit: 6,
        scale: [1, 2, 3, 4, 5, 6, 8, 10, 12, 16],
      },
      radius: {
        none: '0px',
        xs: '0px',
        sm: '0px',
        md: '0px',
        lg: '2px',
        xl: '4px',
        xxl: '6px',
        full: '9999px',
        button: 'var(--radius-none)',
      },
      shadows: {
        none: 'none',
        sm: '2px 2px 0px #00ffcc',
        md: '4px 4px 0px #ff0055',
        lg: '6px 6px 0px #ffff00',
        xl: '8px 8px 0px #ff0055, -4px -4px 0px #00ffcc',
        focus: '0 0 0 2px #030308, 0 0 0 4px #00ffcc',
      },
      motion: {
        durationFast: '80ms',
        durationNormal: '150ms',
        durationSlow: '300ms',
        easeDefault: 'linear',
        easeIn: 'linear',
        easeOut: 'linear',
        easeInOut: 'linear',
      },
      icons: {
        sizeSm: '16px',
        sizeMd: '20px',
        sizeLg: '24px',
        strokeWidth: '2.5px',
      },
    },
  },
  {
    id: 'neo-brutalism',
    name: 'Neo-Brutalism (Retro Bold)',
    description: 'Thick raw black borders, offset solid shadows, flat vibrant backgrounds, and raw typography layout. High visual impact.',
    tokens: {
      name: 'Neo Brutal',
      author: 'Raw Craft',
      description: 'Bold retro aesthetics, solid drop shadows, and solid contrast styling.',
      version: '1.0.0',
      targetFramework: 'react-tailwind',
      colors: {
        primary: { light: '#facc15', dark: '#fde047', description: 'Core primary yellow' },
        primaryHover: { light: '#eab308', dark: '#facc15', description: 'Primary action hover' },
        secondary: { light: '#fdba74', dark: '#fed7aa', description: 'Accent peach secondary' },
        secondaryHover: { light: '#f97316', dark: '#fdba74', description: 'Secondary action hover' },
        accent: { light: '#f43f5e', dark: '#fb7185', description: 'Brutal accent pink' },
        bg: { light: '#f3f4f6', dark: '#18181b', description: 'Page background' },
        card: { light: '#ffffff', dark: '#27272a', description: 'Brutal card container' },
        border: { light: '#000000', dark: '#ffffff', description: 'Heavy solid borders' },
        text: { light: '#000000', dark: '#ffffff', description: 'Body copy text color' },
        textMuted: { light: '#374151', dark: '#d1d5db', description: 'Secondary brutal info' },
        success: { light: '#4ade80', dark: '#4ade80', description: 'Positive alert background' },
        warning: { light: '#fb923c', dark: '#fb923c', description: 'Caution state' },
        error: { light: '#f87171', dark: '#f87171', description: 'Failing checks status' },
        info: { light: '#60a5fa', dark: '#60a5fa', description: 'Info panel background' },
      },
      typography: {
        fontFamily: "'Inter', system-ui, sans-serif",
        baseSize: 16,
        scaleFactor: 1.25, // Major Third
        lineHeight: '1.4',
        letterSpacing: '-0.02em',
      },
      spacing: {
        baseUnit: 8,
        scale: [1, 2, 3, 4, 6, 8, 10, 12, 16],
      },
      radius: {
        none: '0px',
        xs: '2px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '24px',
        full: '9999px',
        button: 'var(--radius-none)',
      },
      shadows: {
        none: 'none',
        sm: '2px 2px 0px #000000',
        md: '4px 4px 0px #000000',
        lg: '8px 8px 0px #000000',
        xl: '12px 12px 0px #000000',
        focus: '0 0 0 2px #ffffff, 0 0 0 5px #000000',
      },
      motion: {
        durationFast: '100ms',
        durationNormal: '200ms',
        durationSlow: '350ms',
        easeDefault: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        easeIn: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        easeOut: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        easeInOut: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
      },
      icons: {
        sizeSm: '16px',
        sizeMd: '20px',
        sizeLg: '24px',
        strokeWidth: '2.5px',
      },
    },
  },
  {
    id: 'glassmorphism',
    name: 'Future Glassmorphism',
    description: 'Translucent panels, heavy backdrop-blur filters, subtle neon border overlays, and smooth animations. Captures an OS X / iOS look.',
    tokens: {
      name: 'Glass System',
      author: 'Vapor Core',
      description: 'Overlay panel system with deep blur layers and pastel violet/pink backdrops.',
      version: '1.2.0',
      targetFramework: 'react-tailwind',
      colors: {
        primary: { light: '#ec4899', dark: '#f472b6', description: 'Pastel magenta action' },
        primaryHover: { light: '#db2777', dark: '#ec4899', description: 'Magenta action hover' },
        secondary: { light: '#06b6d4', dark: '#22d3ee', description: 'Cyber pastel blue' },
        secondaryHover: { light: '#0891b2', dark: '#06b6d4', description: 'Blue hover' },
        accent: { light: '#8b5cf6', dark: '#a78bfa', description: 'Glowing purple highlight' },
        bg: { light: '#f5f3ff', dark: '#02000a', description: 'Canvas backdrop (gradient-ready)' },
        card: { light: 'rgba(255, 255, 255, 0.35)', dark: 'rgba(15, 10, 30, 0.45)', description: 'Frosted glass container' },
        border: { light: 'rgba(255, 255, 255, 0.45)', dark: 'rgba(255, 255, 255, 0.08)', description: 'Translucent glass border line' },
        text: { light: '#1e1b4b', dark: '#f3e8ff', description: 'Frosted text' },
        textMuted: { light: '#5c5a82', dark: '#bebcd9', description: 'Muted text' },
        success: { light: '#10b981', dark: '#34d399', description: 'Glass green success shadow' },
        warning: { light: '#fbbf24', dark: '#fbbf24', description: 'Glass gold warning shadow' },
        error: { light: '#f87171', dark: '#f87171', description: 'Glass red error shadow' },
        info: { light: '#60a5fa', dark: '#60a5fa', description: 'Glass blue info shadow' },
      },
      typography: {
        fontFamily: "'Inter', sans-serif",
        baseSize: 16,
        scaleFactor: 1.2, // Minor third
        lineHeight: '1.6',
        letterSpacing: '-0.01em',
      },
      spacing: {
        baseUnit: 4,
        scale: [1, 2, 3, 4, 6, 8, 12, 16, 20, 24],
      },
      radius: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '32px',
        full: '9999px',
        button: 'var(--radius-md)',
      },
      shadows: {
        none: 'none',
        sm: '0 4px 30px rgba(0, 0, 0, 0.03)',
        md: '0 8px 32px 0 rgba(139, 92, 246, 0.12)',
        lg: '0 8px 32px 0 rgba(31, 38, 135, 0.25)',
        xl: '0 12px 40px 0 rgba(0, 0, 0, 0.3)',
        focus: '0 0 0 3px rgba(236, 72, 153, 0.45)',
      },
      motion: {
        durationFast: '200ms',
        durationNormal: '350ms',
        durationSlow: '600ms',
        easeDefault: 'cubic-bezier(0.25, 0.8, 0.25, 1)',
        easeIn: 'cubic-bezier(0.25, 0.8, 0.25, 1)',
        easeOut: 'cubic-bezier(0.25, 0.8, 0.25, 1)',
        easeInOut: 'cubic-bezier(0.25, 0.8, 0.25, 1)',
      },
      icons: {
        sizeSm: '14px',
        sizeMd: '20px',
        sizeLg: '28px',
        strokeWidth: '1.5px',
      },
    },
  },
  {
    id: 'nordic-minimalist',
    name: 'Nordic Minimalist (Sage & Cream)',
    description: 'Clean, natural Scandinavian aesthetic. Sage green actions, warm cream surfaces, and spacious rounded borders.',
    tokens: {
      name: 'Nordic Cabin',
      author: 'Hygee Design',
      description: 'Organic green accents and warm cream linen tones for relaxing interfaces.',
      version: '1.0.0',
      targetFramework: 'react-tailwind',
      colors: {
        primary: { light: '#2d5a27', dark: '#568b6d', description: 'Organic forest green' },
        primaryHover: { light: '#21431d', dark: '#467259', description: 'Forest green hover' },
        secondary: { light: '#8fa89b', dark: '#b2c5bb', description: 'Sage auxiliary' },
        secondaryHover: { light: '#738d7f', dark: '#9bb1a5', description: 'Sage hover' },
        accent: { light: '#c2b092', dark: '#d7caa8', description: 'Warm sand highlight' },
        bg: { light: '#faf8f5', dark: '#141c18', description: 'Warm cream linen backdrop' },
        card: { light: '#ffffff', dark: '#1c2621', description: 'Pristine wood surface' },
        border: { light: '#e5e2db', dark: '#2e3a34', description: 'Soft organic border' },
        text: { light: '#1e2522', dark: '#ebf2ee', description: 'Deep forest charcoal text' },
        textMuted: { light: '#5e6863', dark: '#8aa396', description: 'Muted forest details' },
        success: { light: '#38761d', dark: '#6aa84f', description: 'Validation success' },
        warning: { light: '#b45f06', dark: '#e69138', description: 'Validation warning' },
        error: { light: '#990000', dark: '#cc0000', description: 'Validation error' },
        info: { light: '#3c78d8', dark: '#6d9eeb', description: 'Validation details' },
      },
      typography: {
        fontFamily: "'Lora', 'Inter', serif",
        baseSize: 16,
        scaleFactor: 1.25, // Major Third
        lineHeight: '1.6',
        letterSpacing: '-0.015em',
      },
      spacing: {
        baseUnit: 6,
        scale: [1, 2, 3, 4, 6, 8, 10, 12, 16],
      },
      radius: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '32px',
        full: '9999px',
        button: 'var(--radius-xl)',
      },
      shadows: {
        none: 'none',
        sm: '0 2px 4px rgba(0,0,0,0.02)',
        md: '0 4px 10px rgba(0,0,0,0.03)',
        lg: '0 8px 24px rgba(0,0,0,0.04)',
        xl: '0 16px 40px rgba(0,0,0,0.05)',
        focus: '0 0 0 3px rgba(45,90,39,0.3)',
      },
      motion: {
        durationFast: '180ms',
        durationNormal: '280ms',
        durationSlow: '450ms',
        easeDefault: 'cubic-bezier(0.16, 1, 0.3, 1)',
        easeIn: 'cubic-bezier(0.16, 1, 0.3, 1)',
        easeOut: 'cubic-bezier(0.16, 1, 0.3, 1)',
        easeInOut: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      icons: {
        sizeSm: '14px',
        sizeMd: '20px',
        sizeLg: '26px',
        strokeWidth: '1.75px',
      },
    },
  },
  {
    id: 'fallout-terminal',
    name: 'Fallout Terminal (CRT Phosphor)',
    description: 'Retro amber/green phosphor terminal mockup with sharp corners, monospace readouts, and neon glowing borders.',
    tokens: {
      name: 'Mainframe CRT',
      author: 'Vault Tech',
      description: 'High-contrast retro monospace layouts simulating glowing cathode ray tube monitors.',
      version: '2.8.1',
      targetFramework: 'react-tailwind',
      colors: {
        primary: { light: '#ffb000', dark: '#39ff14', description: 'Phosphor emitter color' },
        primaryHover: { light: '#cca300', dark: '#2fe010', description: 'Phosphor hover' },
        secondary: { light: '#ffc133', dark: '#63ff44', description: 'CRT sub-readouts' },
        secondaryHover: { light: '#ffb000', dark: '#39ff14', description: 'CRT sub hover' },
        accent: { light: '#ff3300', dark: '#ff3300', description: 'Critical system alarm red' },
        bg: { light: '#080808', dark: '#000000', description: 'Dark CRT glass background' },
        card: { light: '#141414', dark: '#030303', description: 'System core blocks' },
        border: { light: '#ffb000', dark: '#39ff14', description: 'Glow boundary lines' },
        text: { light: '#ffb000', dark: '#39ff14', description: 'Monospace screen readouts' },
        textMuted: { light: '#b37c00', dark: '#24a30e', description: 'Muted log variables' },
        success: { light: '#39ff14', dark: '#39ff14', description: 'Success flag' },
        warning: { light: '#ffb000', dark: '#ffb000', description: 'Warning flag' },
        error: { light: '#ff3300', dark: '#ff3300', description: 'Core error flag' },
        info: { light: '#39ff14', dark: '#39ff14', description: 'Sys notification' },
      },
      typography: {
        fontFamily: "'JetBrains Mono', monospace",
        baseSize: 14,
        scaleFactor: 1.15, // Golden ratio small
        lineHeight: '1.3',
        letterSpacing: '0.05em',
      },
      spacing: {
        baseUnit: 6,
        scale: [1, 2, 3, 4, 6, 8, 10, 12, 16],
      },
      radius: {
        none: '0px',
        xs: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        xxl: '0px',
        full: '9999px',
        button: 'var(--radius-none)',
      },
      shadows: {
        none: 'none',
        sm: '2px 2px 0px rgba(57,255,20,0.2)',
        md: '4px 4px 0px rgba(57,255,20,0.3)',
        lg: '6px 6px 0px rgba(57,255,20,0.4)',
        xl: '8px 8px 0px rgba(57,255,20,0.5)',
        focus: '0 0 0 3px rgba(57,255,20,0.6)',
      },
      motion: {
        durationFast: '50ms',
        durationNormal: '120ms',
        durationSlow: '250ms',
        easeDefault: 'linear',
        easeIn: 'linear',
        easeOut: 'linear',
        easeInOut: 'linear',
      },
      icons: {
        sizeSm: '16px',
        sizeMd: '20px',
        sizeLg: '24px',
        strokeWidth: '2.5px',
      },
    },
  },
  {
    id: 'luxury-editorial',
    name: 'Luxury Editorial (Brass & Ivory)',
    description: 'Elegant high-fashion brand feel. Warm ivory backdrop, deep espresso black cards, and brass gold accents.',
    tokens: {
      name: 'Editorial Vogue',
      author: 'Luxury Architect',
      description: 'Elegant Serif typographies and premium brass colors for high-end digital lifestyle magazines.',
      version: '1.0.0',
      targetFramework: 'react-tailwind',
      colors: {
        primary: { light: '#c5a880', dark: '#d7c0a3', description: 'Polished brass accent' },
        primaryHover: { light: '#b3956c', dark: '#c5a880', description: 'Brass accent hover' },
        secondary: { light: '#524d49', dark: '#a59e9a', description: 'Espresso gray secondary' },
        secondaryHover: { light: '#3e3936', dark: '#8f8884', description: 'Espresso hover' },
        accent: { light: '#131111', dark: '#ffffff', description: 'High-contrast focal color' },
        bg: { light: '#faf6f0', dark: '#0f0d0e', description: 'Ivory linen background' },
        card: { light: '#ffffff', dark: '#1a1819', description: 'Polished card surface' },
        border: { light: '#eae2d5', dark: '#2c2729', description: 'Clean luxury divider' },
        text: { light: '#131111', dark: '#faf6f0', description: 'High contrast text copy' },
        textMuted: { light: '#5e5652', dark: '#a59e9a', description: 'Muted editorial caption' },
        success: { light: '#2e5a44', dark: '#487c63', description: 'Validation success' },
        warning: { light: '#997300', dark: '#cc9900', description: 'Validation warning' },
        error: { light: '#800000', dark: '#b30000', description: 'Validation error' },
        info: { light: '#1a365d', dark: '#2b4c7e', description: 'Validation info' },
      },
      typography: {
        fontFamily: "'Playfair Display', 'Lora', serif",
        baseSize: 16,
        scaleFactor: 1.33, // Perfect Fourth
        lineHeight: '1.5',
        letterSpacing: '-0.02em',
      },
      spacing: {
        baseUnit: 4,
        scale: [1, 2, 3, 4, 6, 8, 10, 12, 16],
      },
      radius: {
        none: '0px',
        xs: '2px',
        sm: '4px',
        md: '4px',
        lg: '6px',
        xl: '8px',
        xxl: '12px',
        full: '9999px',
        button: 'var(--radius-none)',
      },
      shadows: {
        none: 'none',
        sm: '0 2px 8px rgba(0,0,0,0.03)',
        md: '0 4px 16px rgba(0,0,0,0.04)',
        lg: '0 8px 24px rgba(0,0,0,0.05)',
        xl: '0 16px 48px rgba(0,0,0,0.06)',
        focus: '0 0 0 3px rgba(197,168,128,0.4)',
      },
      motion: {
        durationFast: '250ms',
        durationNormal: '400ms',
        durationSlow: '700ms',
        easeDefault: 'cubic-bezier(0.25, 1, 0.5, 1)',
        easeIn: 'cubic-bezier(0.25, 1, 0.5, 1)',
        easeOut: 'cubic-bezier(0.25, 1, 0.5, 1)',
        easeInOut: 'cubic-bezier(0.25, 1, 0.5, 1)',
      },
      icons: {
        sizeSm: '14px',
        sizeMd: '20px',
        sizeLg: '26px',
        strokeWidth: '1.25px',
      },
    },
  },
  {
    id: 'midnight-aurora',
    name: 'Midnight Aurora (Arctic Teal)',
    description: 'Deep northern lights aesthetic. Arctic blue backdrops, glowing teal actions, and cosmic purple accents.',
    tokens: {
      name: 'Aurora Borealis',
      author: 'Cosmic Creator',
      description: 'Deep dark themes lit up by beautiful northern lights neon sky gradients.',
      version: '1.2.0',
      targetFramework: 'react-tailwind',
      colors: {
        primary: { light: '#0d9488', dark: '#22d3ee', description: 'Teal sky emitter' },
        primaryHover: { light: '#0f766e', dark: '#06b6d4', description: 'Teal hover' },
        secondary: { light: '#7c3aed', dark: '#a78bfa', description: 'Aurora violet secondary' },
        secondaryHover: { light: '#6d28d9', dark: '#8b5cf6', description: 'Aurora hover' },
        accent: { light: '#db2777', dark: '#ec4899', description: 'Cosmic pink highlight' },
        bg: { light: '#f0fdfa', dark: '#030712', description: 'Icy dark sky backdrop' },
        card: { light: '#ffffff', dark: '#0f172a', description: 'Polar research surface' },
        border: { light: '#ccfbef', dark: '#1e293b', description: 'Subtle frost dividers' },
        text: { light: '#0f172a', dark: '#f8fafc', description: 'Crystal bright text' },
        textMuted: { light: '#567670', dark: '#94a3b8', description: 'Muted atmospheric details' },
        success: { light: '#10b981', dark: '#34d399', description: 'Atmospheric success glow' },
        warning: { light: '#f59e0b', dark: '#fbbf24', description: 'Atmospheric warning glow' },
        error: { light: '#ef4444', dark: '#f87171', description: 'Atmospheric error glow' },
        info: { light: '#3b82f6', dark: '#60a5fa', description: 'Atmospheric info glow' },
      },
      typography: {
        fontFamily: "'Inter', sans-serif",
        baseSize: 16,
        scaleFactor: 1.2, // Minor third
        lineHeight: '1.5',
        letterSpacing: '-0.012em',
      },
      spacing: {
        baseUnit: 4,
        scale: [1, 2, 3, 4, 5, 6, 8, 10, 12, 16],
      },
      radius: {
        none: '0px',
        xs: '4px',
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '18px',
        xxl: '24px',
        full: '9999px',
        button: 'var(--radius-lg)',
      },
      shadows: {
        none: 'none',
        sm: '0px 1px 3px rgba(0, 240, 255, 0.05)',
        md: '0px 4px 12px rgba(0, 240, 255, 0.08)',
        lg: '0px 8px 24px rgba(139, 92, 246, 0.15)',
        xl: '0px 16px 40px rgba(139, 92, 246, 0.25)',
        focus: '0 0 0 3px rgba(34,211,238,0.5)',
      },
      motion: {
        durationFast: '120ms',
        durationNormal: '220ms',
        durationSlow: '400ms',
        easeDefault: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        easeIn: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        easeOut: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        easeInOut: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
      },
      icons: {
        sizeSm: '14px',
        sizeMd: '20px',
        sizeLg: '26px',
        strokeWidth: '1.75px',
      },
    },
  },
];
